### ISSUE TITLE
`test_sh` failing on alpine

### ISSUE THREAD

**Issue by eddsalkield** [sahib/rmlint#593]
Currently many `test_sh` tests fail on Alpine (x86_64, v2.10.1) with e.g.:

```
$ scons test
...
======================================================================
ERROR: test_sh.test_remove_empty_dirs('dash', True, {})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3.10/site-packages/parameterized/parameterized.py", line 404, in <lambda>
    nose_func = wraps(func)(lambda *args: func(*args[:-1], **args[-1]))
  File "/home/edd/dev/aports/testing/rmlint/src/rmlint-2.10.1/tests/test_formatters/test_sh.py", line 207, in test_remove_empty_dirs
    _check_if_empty_dirs_deleted(shell, inverse_order, sh_path, data)
  File "/home/edd/dev/aports/testing/rmlint/src/rmlint-2.10.1/tests/test_formatters/test_sh.py", line 166, in _check_if_empty_dirs_deleted
    run_shell_script(shell, sh_path, "-dc")
  File "/home/edd/dev/aports/testing/rmlint/src/rmlint-2.10.1/tests/test_formatters/test_sh.py", line 12, in run_shell_script
    return subprocess.check_output([
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/bin/dash'
```

This is because [it's expecting the `dash` shell at `/bin/dash`](https://github.com/sahib/rmlint/blob/2711b84bb264b41015d718b06b0e5be065d42ebc/tests/test_formatters/test_sh.py#L13), whereas alpine installs it at `/usr/bin/dash`. Maybe we could add a simple bit of logic to check `/usr/bin` as well, or alternatively find the binaries using `$PATH`?

**Comment by fermino** [comment]
Given the differences in glibc and musl we should probably aim to add Alpine (or other musl based distro) in the test suite, not only building but the whole thing.

**Comment by RayOei** [comment]
> add Alpine (or other musl based distro) in the test suite

I think we can add this to the list in #700 ?

**Comment by vassilit** [comment]
Similar to #713, interpreter paths are not guessed correctly

**Comment by vassilit** [comment]
> Given the differences in glibc and musl 

A bit off-topic, but do you have any idea why we include our own FTS implementation in 41abdca ?

I understand that 2015 FTS implementation in libc was not the same as the one we have today.

**Comment by fermino** [comment]
> A bit off-topic, but do you have any idea why we include our own FTS implementation in [41abdca](https://github.com/sahib/rmlint/commit/41abdca38912192208e12867d0d584d8ad72e306) ?
> 
> I understand that 2015 FTS implementation in libc was not the same as the one we have today.

Not the slightest clue, I was just referring to the general differences in implementation. 

@sahib it might be a long shot as that commit is from 2015, but do you happen to remember the reason behind it?

I'm all in to remove it (i.e. simplify things), but only if we can make sure that things will keep working properly, everywhere.
